#!/usr/bin/env bash
set -o errexit
set -o nounset

DEV_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
PROJECT_ROOT="${DEV_DIR}/.."
BUILD_DIR="${PROJECT_ROOT}/.build/"

cd "${PROJECT_ROOT}"
set -x
${DEV_DIR}/clean
time npm install
mkdir -p ${BUILD_DIR}
ln -s "${PROJECT_ROOT}/node_modules" "${BUILD_DIR}/node_modules"
time ${PROJECT_ROOT}/node_modules/.bin/babel . --out-dir "${BUILD_DIR}"
cp "${PROJECT_ROOT}/package.json" "${BUILD_DIR}/package.json"