#!/usr/bin/env bash
set -o errexit
set -o nounset

DEV_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
set -x
rm -rf "${DEV_DIR}/../.build"
# rm -rf "${DEV_DIR}/../node_modules"