#!/usr/bin/env bash
set -o errexit
set -o nounset

DEV_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
${DEV_DIR}/build
set -x
nohup firebase emulators:start --inspect-functions > /dev/null 2>&1 &
nohup xdg-open http://localhost:5000/forum > /dev/null 2>&1 &