#!/usr/bin/env bash
set -o errexit
set -o nounset

DEV_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

cd "${DEV_DIR}/.."
firebase emulators:export --force "${DEV_DIR}/../test/data/"
